def output():
    #window = Tk()
    topframe.pack_forget()
    aa=Label(text="hello")
    aa.pack()
    #window.geometry("200x100")
    #window.mainloop()
from tkinter import *
root = Tk()
topframe = Frame(root)
topframe.pack()
bottomframe=Frame(root)
bottomframe.pack(side=BOTTOM)
root.title("hello")
aa= Label(bottomframe,text="what is happening")
aa.pack(side=LEFT)
but1=Button(topframe,text="but 1",command=output)
but2=Button(topframe,text="but 2")
but3=Button(topframe,text="but 3")
but4=Button(bottomframe,text="but 4")
but1.pack(side=LEFT)
but2.pack(side=LEFT)
but3.pack(side=LEFT)
but4.pack(side=BOTTOM)
root.geometry("200x100")
root.mainloop()
